trigger: none

# The `resources` specify the location and version of the 1ES PT.
resources:
  pipelines:
  - pipeline: 'pod'
    project: 'Lotus'
    source: 'onnxruntime-ios-packaging-pipeline'
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: Azure Pipelines
      image: "macOS-13"
      os: macOS      
    sdl:
      sourceAnalysisPool:
        name: onnxruntime-Win-CPU-2022
        os: windows
      policheck:
        enabled: true
      credscan:
        enabled: true
      codeql:
        sourceLanguages: python
      tsa:
        enabled: true
        configFile: '$(Build.SourcesDirectory)\.config\tsaoptions.json'
    stages:
    - stage: Stage
      jobs:
      - template: .pipelines/templates/main.yml@self